.pc
.TH "bdf2c" 1 "2009-02-16" "1" "bdf2c Manual"

.SH NAME
bdf2c \- converts bdf font files into C include files

.SH SYNOPSIS
.B bdf2c
.I [-?|-h]
.I [-c]
.I [-C file]
.I [-b]

.SH DESCRIPTION


.SH OPTIONS
.TP
.B -?|-h
Show help options.
.TP

.SH AUTHOR
Johns (2009) <johns98@gmx.net>.

.SH COPYRIGHT
Copyright (C) 2009 Johns.  License: AGPLv3
